services:

  ovos-assist-agent:
    image: ovos-persona/ovos-core
    restart: always
    container_name: ovos_core_persona
    # network_mode: host in order to be able to connect to the bus
    network_mode: host
    #ports:
    #  - 8337:8337
    
  wyoming-ovos-tts-sam:
    image: jarbasai/ovos-wyoming-tts-sam:latest
    container_name: wyoming-ovos-tts-sam
    restart: unless-stopped
    volumes:
      - ${CONFIG_BASE_DIR}/mycroft.conf:/etc/mycroft/mycroft.conf
    ports:
      - 10605:8080
  wyoming-ovos-tts-nos:
    image: jarbasai/ovos-wyoming-tts-nos:latest
    container_name: wyoming-ovos-tts-nos
    restart: unless-stopped
    volumes:
      - ${CONFIG_BASE_DIR}/mycroft.conf:/etc/mycroft/mycroft.conf
    ports:
      - 10604:8080
  wyoming-ovos-tts-mimic:
    image: jarbasai/ovos-wyoming-tts-mimic:latest
    container_name: wyoming-ovos-tts-mimic
    restart: unless-stopped
    volumes:
      - ${CONFIG_BASE_DIR}/mycroft.conf:/etc/mycroft/mycroft.conf
    ports:
      - 10603:8080
  wyoming-ovos-tts-google-tx:
    image: jarbasai/ovos-wyoming-tts-google-tx:latest
    container_name: wyoming-ovos-tts-google-tx
    restart: unless-stopped
    volumes:
      - ${CONFIG_BASE_DIR}/mycroft.conf:/etc/mycroft/mycroft.conf
    ports:
      - 10602:8080
  wyoming-ovos-tts-matxa:
    image: jarbasai/ovos-wyoming-tts-matxa:latest
    container_name: wyoming-ovos-tts-matxa
    restart: unless-stopped
    volumes:
      - ${CONFIG_BASE_DIR}/mycroft.conf:/etc/mycroft/mycroft.conf
    ports:
      - 10601:8080
  wyoming-ovos-tts-servers:
    build:
      context: ./tts-servers
      dockerfile: Dockerfile
    image: jarbasai/ovos-wyoming-tts-servers:latest
    container_name: wyoming-ovos-tts-servers
    restart: unless-stopped
    volumes:
      - ${CONFIG_BASE_DIR}/mycroft.conf:/etc/mycroft/mycroft.conf
    ports:
      - 10600:8080
  wyoming-ovos-stt-servers:
    build:
      context: ./stt-servers
      dockerfile: Dockerfile
    image: jarbasai/ovos-wyoming-stt-servers:latest
    container_name: wyoming-ovos-stt-servers
    restart: unless-stopped
    volumes:
      - ${CONFIG_BASE_DIR}/mycroft.conf:/etc/mycroft/mycroft.conf
    ports:
      - 10501:8080
  wyoming-ovos-chromium-stt:
    build:
      context: ./stt-chromium
      dockerfile: Dockerfile
    image: jarbasai/ovos-wyoming-chromium:latest
    container_name: wyoming-ovos-chromium-stt
    restart: unless-stopped
    volumes:
      - ${CONFIG_BASE_DIR}/mycroft.conf:/etc/mycroft/mycroft.conf
    ports:
      - 10500:8080
  wyoming-ovos-wakewords:
    build:
      context: ./ww
      dockerfile: Dockerfile
    container_name: wyoming-ovos-wakewords
    image: jarbasai/ovos-wyoming-wakewords:latest
    volumes:
      - ${CONFIG_BASE_DIR}/mycroft.conf:/etc/mycroft/mycroft.conf
    ports:
      - 10900:8080
